1. En el archivo de servicio, se puede usar un bloque `try-catch` para manejar errores en una solicitud HTTP:

```ts
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({
	providedIn: 'root'
})
export class DataService {
	private apiUrl = 'https://mi-api.com';
	
	constructor(private http: HttpClient) {}
	
	getData() {
		try {
			return this.http.get(this.apiUrl);
		} catch (error) {
		console.log('Error en la solicitud HTTP:', error.message);
	    }
	}
}
```

2. En el archivo de componente, se puede utilizar el método `subscribe()` para manejar la respuesta y el error de una solicitud HTTP y mostrar un mensaje de error en caso de que algo salga mal:

```ts
import { Component } from '@angular/core';
import { DataService } from './data.service';

@Component({
	selector: 'app-my-component',
	templateUrl: './my-component.component.html',
	styleUrls: ['./my-component.component.css']
})
export class MyComponent {
	data: any;
	errorMsg: string;
	
	constructor(private dataService: DataService) {}
	
	ngOnInit() {
		this.dataService.getData().subscribe(
			response => {
				this.data = response;
			},
			error => {
				this.errorMsg = 'Hubo un error al obtener los datos: ' + error.message;
			}
		);
	}
}
```

En este ejemplo, el método `subscribe()` se utiliza para manejar tanto la respuesta como el error de la solicitud HTTP. Si ocurre un error al obtener los datos, se muestra un mensaje de error en una propiedad errorMsg en el componente, que se puede mostrar en la vista.

Es importante mencionar que esta es solo una manera de manejar errores en Angular y que hay muchas otras formas. También es recomendable manejar y registrar errores de forma consistente en toda la aplicación usando bibliotecas de registro de errores, como Sentry o Rollbar.